deployScripts:
  start:
    - npm install --unsafe-perm=true --allow-root
    - npm run compile
    - pm2 start ./pm2.json
  delete:
    - pm2 delete nideshop
  restart:
    - npm install --unsafe-perm=true --allow-root
    - npm run compile
    - pm2 restart hioshop
